# California Revenue and Taxation Code Section 17052.1
# Young Child Tax Credit (YCTC) Parameters
#
# Source: FTB Young Child Tax Credit
# Reference: https://www.ftb.ca.gov/file/personal/credits/young-child-tax-credit.html
#
# YCTC is a refundable tax credit for families with qualifying children under age 6.
# Parameters are adjusted annually for inflation.

metadata:
  statute: "CA RTC 17052.1"
  description: "Young Child Tax Credit amounts and thresholds"
  reference:
    - "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=17052.1&lawCode=RTC"
    - "https://www.ftb.ca.gov/file/personal/credits/young-child-tax-credit.html"

# =============================================================================
# Maximum Credit Amount
# Note: Credit is per TAX RETURN, not per qualifying child
# =============================================================================

gov.ca.ftb.yctc.max_credit:
  description: "Maximum Young Child Tax Credit per tax return"
  unit: "USD"

  values:
    2023-01-01: 1117
    2024-01-01: 1154
    2025-01-01: 1189    # Projected 3.1% increase
    2026-01-01: 1219    # Projected 2.5% increase

  reference: "CA RTC 17052.1, FTB Form 3514"

# =============================================================================
# Income Threshold (Full Credit Below This Amount)
# =============================================================================

gov.ca.ftb.yctc.income_threshold:
  description: "Earned income threshold below which full YCTC is available"
  unit: "USD"

  values:
    2023-01-01: 25803
    2024-01-01: 26626
    2025-01-01: 27438   # Projected 3.1% increase
    2026-01-01: 28124   # Projected 2.5% increase

  reference: "FTB Form 3514 Instructions"

# =============================================================================
# Maximum Income (Credit Phases Out Completely Above This)
# =============================================================================

gov.ca.ftb.yctc.max_income:
  description: "Maximum earned income to receive any YCTC"
  unit: "USD"

  values:
    2023-01-01: 30950
    2024-01-01: 32900
    2025-01-01: 33951   # Projected 3.1% increase
    2026-01-01: 34800   # Projected 2.5% increase

  reference: "FTB Form 3514 Instructions"

# =============================================================================
# Phase-Out Reduction Per $100 of Excess Income
# =============================================================================

gov.ca.ftb.yctc.reduction_per_100:
  description: "Credit reduction for each $100 of earned income over threshold"
  unit: "USD"

  values:
    # This amount remains relatively stable as it's derived from the
    # relationship between max_credit and (max_income - income_threshold)
    2023-01-01: 21.67
    2024-01-01: 21.67
    2025-01-01: 21.67
    2026-01-01: 21.67

  reference: "FTB Form 3514 Instructions"

# =============================================================================
# Age Limit for Qualifying Child
# =============================================================================

gov.ca.ftb.yctc.child_age_limit:
  description: "Child must be under this age at end of tax year to qualify"
  unit: "years"

  values:
    2019-01-01: 6  # Must be under age 6 (i.e., 5 or younger)

  reference: "CA RTC 17052.1(b)"

# =============================================================================
# Notes on YCTC Eligibility
# =============================================================================

# - YCTC is fully refundable
# - Credit is per tax return, not per qualifying child
# - Must have at least one qualifying child under age 6 at end of tax year
# - Originally required CalEITC eligibility (2019-2021)
# - Beginning 2022, eligibility expanded:
#   - Taxpayers may have net loss and still qualify
#   - Can qualify even without CalEITC if within YCTC income limits
# - Cannot use ITIN if child was not born in the US (citizenship requirement)
# - Phase-out calculation: for every $100 over income_threshold,
#   credit reduces by reduction_per_100 amount
