# California Revenue and Taxation Code ยง 17052.1
# Young Child Tax Credit (YCTC) Parameters
#
# Source: FTB Young Child Tax Credit
# https://www.ftb.ca.gov/file/personal/credits/young-child-tax-credit.html

variable: yctc
description: Young Child Tax Credit amounts and thresholds

# 2024 Tax Year
# Source: FTB 2024 Form 3514 Instructions
2024:
  # Maximum credit per tax return (not per child)
  max_credit: 1154

  # Income threshold - full credit below this amount
  income_threshold: 26626

  # Maximum earned income to qualify
  max_income: 32900

  # Credit reduction per $100 of income over threshold
  reduction_per_100: 21.67

  # Age requirement
  child_age_limit: 6  # Under 6 at end of tax year

# 2023 Tax Year (for reference)
2023:
  max_credit: 1117
  income_threshold: 25803
  max_income: 30950
  reduction_per_100: 21.67
  child_age_limit: 6

# 2025 Tax Year (announced)
2025:
  max_credit: 1189
  income_threshold: 27438
  max_income: 33951
  reduction_per_100: 21.67
  child_age_limit: 6

# Notes:
# - YCTC is fully refundable
# - Must also qualify for CalEITC to receive YCTC
# - Credit is per tax return, not per qualifying child
# - Beginning in 2022, taxpayers may have net loss and still qualify
# - Can have $0 or even negative earned income if within loss threshold
