# California Revenue and Taxation Code Section 17041
# Personal Income Tax Rate Schedules
#
# Source: FTB Tax Rate Schedules
# https://www.ftb.ca.gov/forms/2024/2024-540-tax-rate-schedules.pdf
#
# California has 9 marginal tax brackets ranging from 1% to 12.3%.
# Bracket thresholds are adjusted annually for inflation.

metadata:
  statute: "CA RTC 17041"
  description: "California personal income tax bracket thresholds by filing status"
  reference:
    - "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=17041&lawCode=RTC"
    - "https://www.ftb.ca.gov/forms/2024/2024-540-tax-rate-schedules.pdf"

# Tax rates are fixed in statute (9 brackets)
# These rates have not changed since 2012
gov.ca.ftb.income_tax.rates:
  description: "California personal income tax marginal rates (9 brackets)"
  unit: "/1"
  values:
    2012-01-01:
      - 0.01     # 1%
      - 0.02     # 2%
      - 0.04     # 4%
      - 0.06     # 6%
      - 0.08     # 8%
      - 0.093    # 9.3%
      - 0.103    # 10.3%
      - 0.113    # 11.3%
      - 0.123    # 12.3%
  reference: "CA RTC 17041(a)"

# =============================================================================
# 2024 Tax Year Thresholds
# Source: FTB 2024 Form 540 Tax Rate Schedules
# =============================================================================

gov.ca.ftb.income_tax.brackets.2024:
  single:
    # Schedule X - Single or Married/RDP Filing Separately
    description: "Single filer bracket thresholds for 2024"
    thresholds:
      - 0           # 1% bracket starts at $0
      - 10756       # 2% bracket starts at $10,756
      - 25499       # 4% bracket starts at $25,499
      - 40245       # 6% bracket starts at $40,245
      - 55866       # 8% bracket starts at $55,866
      - 70606       # 9.3% bracket starts at $70,606
      - 360659      # 10.3% bracket starts at $360,659
      - 432787      # 11.3% bracket starts at $432,787
      - 721314      # 12.3% bracket starts at $721,314
    # Pre-computed tax amounts at each threshold for quick calculation
    tax_at_threshold:
      - 0           # Tax at $0
      - 107.56      # Tax at $10,756
      - 402.42      # Tax at $25,499
      - 992.26      # Tax at $40,245
      - 1929.52     # Tax at $55,866
      - 3108.72     # Tax at $70,606
      - 30083.65    # Tax at $360,659
      - 37506.83    # Tax at $432,787
      - 70108.38    # Tax at $721,314
    reference: "FTB 2024 Form 540 Schedule X"

  married_filing_jointly:
    # Schedule Y - Married/RDP Filing Jointly or Qualifying Surviving Spouse
    description: "MFJ/QSS bracket thresholds for 2024"
    thresholds:
      - 0           # 1% bracket starts at $0
      - 21512       # 2% bracket starts at $21,512
      - 50998       # 4% bracket starts at $50,998
      - 80490       # 6% bracket starts at $80,490
      - 111732      # 8% bracket starts at $111,732
      - 141212      # 9.3% bracket starts at $141,212
      - 721318      # 10.3% bracket starts at $721,318
      - 865574      # 11.3% bracket starts at $865,574
      - 1442628     # 12.3% bracket starts at $1,442,628
    tax_at_threshold:
      - 0
      - 215.12
      - 804.84
      - 1984.52
      - 3859.04
      - 6217.44
      - 60167.30
      - 75025.66
      - 140242.76
    reference: "FTB 2024 Form 540 Schedule Y"

  married_filing_separately:
    # Same as Single (Schedule X)
    description: "MFS bracket thresholds for 2024 (same as Single)"
    thresholds:
      - 0
      - 10756
      - 25499
      - 40245
      - 55866
      - 70606
      - 360659
      - 432787
      - 721314
    tax_at_threshold:
      - 0
      - 107.56
      - 402.42
      - 992.26
      - 1929.52
      - 3108.72
      - 30083.65
      - 37506.83
      - 70108.38
    reference: "FTB 2024 Form 540 Schedule X"

  head_of_household:
    # Schedule Z - Head of Household
    description: "HOH bracket thresholds for 2024"
    thresholds:
      - 0           # 1% bracket starts at $0
      - 21527       # 2% bracket starts at $21,527
      - 51000       # 4% bracket starts at $51,000
      - 65744       # 6% bracket starts at $65,744
      - 81364       # 8% bracket starts at $81,364
      - 96107       # 9.3% bracket starts at $96,107
      - 490493      # 10.3% bracket starts at $490,493
      - 588593      # 11.3% bracket starts at $588,593
      - 980987      # 12.3% bracket starts at $980,987
    tax_at_threshold:
      - 0
      - 215.27
      - 805.19
      - 1394.95
      - 2332.15
      - 3511.59
      - 40200.79
      - 50305.09
      - 94605.71
    reference: "FTB 2024 Form 540 Schedule Z"

  qualifying_surviving_spouse:
    # Same as Married Filing Jointly (Schedule Y)
    description: "QSS bracket thresholds for 2024 (same as MFJ)"
    thresholds:
      - 0
      - 21512
      - 50998
      - 80490
      - 111732
      - 141212
      - 721318
      - 865574
      - 1442628
    tax_at_threshold:
      - 0
      - 215.12
      - 804.84
      - 1984.52
      - 3859.04
      - 6217.44
      - 60167.30
      - 75025.66
      - 140242.76
    reference: "FTB 2024 Form 540 Schedule Y"

# =============================================================================
# 2025 Tax Year Thresholds (Projected)
# Source: FTB inflation adjustment (~3.1% based on CA CCPI)
# Note: Official 2025 values will be published by FTB in late 2024
# =============================================================================

gov.ca.ftb.income_tax.brackets.2025:
  single:
    description: "Single filer bracket thresholds for 2025 (projected)"
    thresholds:
      - 0
      - 11089       # 10,756 * 1.031
      - 26289       # 25,499 * 1.031
      - 41493       # 40,245 * 1.031
      - 57598       # 55,866 * 1.031
      - 72795       # 70,606 * 1.031
      - 371839      # 360,659 * 1.031
      - 446203      # 432,787 * 1.031
      - 743674      # 721,314 * 1.031
    reference: "FTB 2025 projected (3.1% CCPI adjustment)"

  married_filing_jointly:
    description: "MFJ/QSS bracket thresholds for 2025 (projected)"
    thresholds:
      - 0
      - 22179       # 21,512 * 1.031
      - 52579       # 50,998 * 1.031
      - 82985       # 80,490 * 1.031
      - 115196      # 111,732 * 1.031
      - 145609      # 141,212 * 1.031
      - 743678      # 721,318 * 1.031
      - 892407      # 865,574 * 1.031
      - 1487350     # 1,442,628 * 1.031
    reference: "FTB 2025 projected (3.1% CCPI adjustment)"

  married_filing_separately:
    description: "MFS bracket thresholds for 2025 (projected, same as Single)"
    thresholds:
      - 0
      - 11089
      - 26289
      - 41493
      - 57598
      - 72795
      - 371839
      - 446203
      - 743674
    reference: "FTB 2025 projected (3.1% CCPI adjustment)"

  head_of_household:
    description: "HOH bracket thresholds for 2025 (projected)"
    thresholds:
      - 0
      - 22194       # 21,527 * 1.031
      - 52581       # 51,000 * 1.031
      - 67782       # 65,744 * 1.031
      - 83886       # 81,364 * 1.031
      - 99086       # 96,107 * 1.031
      - 505698      # 490,493 * 1.031
      - 606840      # 588,593 * 1.031
      - 1011398      # 980,987 * 1.031
    reference: "FTB 2025 projected (3.1% CCPI adjustment)"

  qualifying_surviving_spouse:
    description: "QSS bracket thresholds for 2025 (projected, same as MFJ)"
    thresholds:
      - 0
      - 22179
      - 52579
      - 82985
      - 115196
      - 145609
      - 743678
      - 892407
      - 1487350
    reference: "FTB 2025 projected (3.1% CCPI adjustment)"

# =============================================================================
# 2026 Tax Year Thresholds (Projected)
# Source: Projected ~2.5% inflation adjustment
# Note: These are rough estimates and will be updated when FTB publishes
# =============================================================================

gov.ca.ftb.income_tax.brackets.2026:
  single:
    description: "Single filer bracket thresholds for 2026 (projected)"
    thresholds:
      - 0
      - 11366       # 11,089 * 1.025
      - 26946       # 26,289 * 1.025
      - 42530       # 41,493 * 1.025
      - 59038       # 57,598 * 1.025
      - 74615       # 72,795 * 1.025
      - 381135      # 371,839 * 1.025
      - 457358      # 446,203 * 1.025
      - 762266      # 743,674 * 1.025
    reference: "FTB 2026 projected (2.5% inflation adjustment)"

  married_filing_jointly:
    description: "MFJ/QSS bracket thresholds for 2026 (projected)"
    thresholds:
      - 0
      - 22733       # 22,179 * 1.025
      - 53893       # 52,579 * 1.025
      - 85060       # 82,985 * 1.025
      - 118076      # 115,196 * 1.025
      - 149249      # 145,609 * 1.025
      - 762270      # 743,678 * 1.025
      - 914717      # 892,407 * 1.025
      - 1524534     # 1,487,350 * 1.025
    reference: "FTB 2026 projected (2.5% inflation adjustment)"

  married_filing_separately:
    description: "MFS bracket thresholds for 2026 (projected, same as Single)"
    thresholds:
      - 0
      - 11366
      - 26946
      - 42530
      - 59038
      - 74615
      - 381135
      - 457358
      - 762266
    reference: "FTB 2026 projected (2.5% inflation adjustment)"

  head_of_household:
    description: "HOH bracket thresholds for 2026 (projected)"
    thresholds:
      - 0
      - 22749       # 22,194 * 1.025
      - 53895       # 52,581 * 1.025
      - 69477       # 67,782 * 1.025
      - 85983       # 83,886 * 1.025
      - 101563      # 99,086 * 1.025
      - 518340      # 505,698 * 1.025
      - 622011      # 606,840 * 1.025
      - 1036683     # 1,011,398 * 1.025
    reference: "FTB 2026 projected (2.5% inflation adjustment)"

  qualifying_surviving_spouse:
    description: "QSS bracket thresholds for 2026 (projected, same as MFJ)"
    thresholds:
      - 0
      - 22733
      - 53893
      - 85060
      - 118076
      - 149249
      - 762270
      - 914717
      - 1524534
    reference: "FTB 2026 projected (2.5% inflation adjustment)"
