# California Revenue and Taxation Code Section 17054
# Standard Deduction Parameters
#
# Source: FTB Form 540 Instructions
# Reference: https://www.ftb.ca.gov/forms/2024/2024-540-booklet.html
#
# California standard deductions are significantly lower than federal.
# These amounts are adjusted annually for inflation (CA CCPI).

metadata:
  statute: "CA RTC 17054"
  description: "California standard deduction amounts by filing status"
  reference:
    - "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=17054&lawCode=RTC"
    - "https://www.ftb.ca.gov/forms/2024/2024-540-booklet.html"

# =============================================================================
# Standard Deduction Amounts
# =============================================================================

gov.ca.ftb.standard_deduction:
  description: "California standard deduction amounts by filing status"
  unit: "USD"

  # 2023 Tax Year
  values:
    2023-01-01:
      single: 5363
      married_filing_separately: 5363
      married_filing_jointly: 10726
      head_of_household: 10726
      qualifying_surviving_spouse: 10726

    # 2024 Tax Year
    # Source: FTB 2024 Form 540 Booklet
    2024-01-01:
      single: 5540
      married_filing_separately: 5540
      married_filing_jointly: 11080
      head_of_household: 11080
      qualifying_surviving_spouse: 11080

    # 2025 Tax Year (Projected - ~3.1% CCPI adjustment)
    2025-01-01:
      single: 5712        # 5,540 * 1.031
      married_filing_separately: 5712
      married_filing_jointly: 11424   # 11,080 * 1.031
      head_of_household: 11424
      qualifying_surviving_spouse: 11424

    # 2026 Tax Year (Projected - ~2.5% inflation adjustment)
    2026-01-01:
      single: 5855        # 5,712 * 1.025
      married_filing_separately: 5855
      married_filing_jointly: 11710   # 11,424 * 1.025
      head_of_household: 11710
      qualifying_surviving_spouse: 11710

  reference: "CA RTC 17054, FTB Form 540 Instructions"

# =============================================================================
# Personal Exemption Credits (RTC 17054.5)
# California uses exemption CREDITS (not deductions) for personal/dependent exemptions
# =============================================================================

gov.ca.ftb.exemption_credit:
  description: "California personal exemption credit amounts"
  unit: "USD"

  values:
    2023-01-01:
      single: 140          # Per taxpayer
      joint: 280           # $140 x 2 for married filing jointly
      dependent: 433       # Per dependent

    2024-01-01:
      single: 144          # Per taxpayer
      joint: 288           # $144 x 2 for married filing jointly
      dependent: 446       # Per dependent

    2025-01-01:
      single: 148          # Projected 3.1% increase
      joint: 296
      dependent: 460

    2026-01-01:
      single: 152          # Projected 2.5% increase
      joint: 304
      dependent: 471

  reference: "CA RTC 17054.5, FTB Form 540 Instructions"

# Note: California standard deductions are significantly lower than federal:
# Federal 2024: $14,600 (single), $29,200 (MFJ)
# California 2024: $5,540 (single), $11,080 (MFJ)
#
# California does not have additional standard deduction for age 65+ or blind.
# Instead, California provides exemption CREDITS that reduce tax liability.
