# California Franchise Tax Board - 2026 Tax Year Parameters (Projected)
#
# Consolidated parameters file for California 2026 tax year.
# These values are PROJECTED based on ~2.5% inflation adjustment.
# Official values will be published by FTB in late 2025.
#
# Source: Projected from 2025 values using estimated inflation
# Note: See statute/rtc/ parameter files for authoritative values

metadata:
  tax_year: 2026
  jurisdiction: CA
  source:
    agency: California Franchise Tax Board (projected)
    url: https://www.ftb.ca.gov
    effective_date: 2026-01-01
  note: "PROJECTED values - official values to be published by FTB"
  inflation_adjustment: 0.025  # 2.5% estimated inflation

# =============================================================================
# Standard Deduction (RTC 17054)
# Projected ~2.5% increase from 2025
# =============================================================================
standard_deduction:
  single: 5855               # 5,712 * 1.025
  married_filing_jointly: 11710  # 11,424 * 1.025
  married_filing_separately: 5855
  head_of_household: 11710
  qualifying_surviving_spouse: 11710

# =============================================================================
# Personal Exemption Credits (RTC 17054.5)
# =============================================================================
exemption_credit:
  single: 152                # 148 * 1.025
  married_filing_jointly: 304
  head_of_household: 152
  dependent: 471             # 460 * 1.025

# =============================================================================
# Mental Health Services Tax (RTC 17043)
# Fixed in statute - NOT indexed for inflation
# =============================================================================
mhs_tax:
  threshold: 1000000  # Fixed since 2005
  rate: 0.01          # 1%

# =============================================================================
# CalEITC (RTC 17052)
# Projected ~2.5% increase from 2025
# =============================================================================
caleitc:
  max_credit:
    children_0: 311          # 303 * 1.025
    children_1: 2069         # 2,019 * 1.025
    children_2: 3423         # 3,339 * 1.025
    children_3_plus: 3851    # 3,757 * 1.025
  max_income: 33764          # 32,940 * 1.025
  investment_income_limit: 4939  # 4,819 * 1.025
  min_earned_income: 1

# =============================================================================
# Young Child Tax Credit (RTC 17052.1)
# Projected ~2.5% increase from 2025
# =============================================================================
yctc:
  max_credit: 1219           # 1,189 * 1.025
  income_threshold: 28124    # 27,438 * 1.025
  max_income: 34800          # 33,951 * 1.025
  child_age_limit: 6
  reduction_per_100: 21.67   # Stable

# =============================================================================
# Foster Youth Tax Credit (RTC 17052.2)
# =============================================================================
fytc:
  max_credit: 1219           # Same as YCTC
  age_minimum: 18
  age_maximum: 25

# =============================================================================
# Renter's Credit (RTC 17081)
# Credit amount frozen, AGI limits indexed
# =============================================================================
renters_credit:
  amount:
    single: 60               # Frozen since 1979
    married_filing_jointly: 120
  agi_limit:
    single: 53627            # 52,319 * 1.025
    married_filing_jointly: 107254  # 104,638 * 1.025

# =============================================================================
# Alternative Minimum Tax (RTC 17062)
# =============================================================================
amt:
  exemption_single: 101295   # 98,824 * 1.025
  exemption_joint: 135065    # 131,770 * 1.025
  exemption_separate: 67534  # 65,887 * 1.025
  phaseout_single: 387320    # 377,873 * 1.025
  phaseout_joint: 516482     # 503,885 * 1.025
  rate: 0.07

# =============================================================================
# Tax Filing Thresholds
# =============================================================================
filing_threshold:
  single: 23948              # 23,364 * 1.025
  married_filing_jointly: 47895  # 46,727 * 1.025
  head_of_household: 36030   # 35,151 * 1.025
  dependent: 7349            # 7,170 * 1.025

# =============================================================================
# State Disability Insurance (SDI)
# =============================================================================
sdi:
  rate: 0.009                # Subject to change
  wage_limit: 161859         # 157,911 * 1.025 (projected)

# =============================================================================
# Income Tax Rate Brackets (RTC 17041)
# Rates fixed, thresholds indexed
# =============================================================================
income_tax_rates:
  - 0.01     # 1%
  - 0.02     # 2%
  - 0.04     # 4%
  - 0.06     # 6%
  - 0.08     # 8%
  - 0.093    # 9.3%
  - 0.103    # 10.3%
  - 0.113    # 11.3%
  - 0.123    # 12.3%
# See statute/rtc/17041/parameters.yaml for complete bracket thresholds
