# California Revenue and Taxation Code Section 17081
# Renter's Credit Parameters
#
# Source: FTB Renter's Credit Information
# Reference: https://www.ftb.ca.gov/file/personal/credits/renters-credit.html
#
# The Renter's Credit is a nonrefundable tax credit for qualifying renters.
# AGI limits are adjusted annually for inflation.

metadata:
  statute: "CA RTC 17081"
  description: "Renter's Credit amounts and AGI limits"
  reference:
    - "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=17081&lawCode=RTC"
    - "https://www.ftb.ca.gov/file/personal/credits/renters-credit.html"

# =============================================================================
# Credit Amounts by Filing Status
# Note: These amounts have been frozen since 1979 and are NOT indexed for inflation
# =============================================================================

gov.ca.ftb.renters_credit.amount:
  description: "Renter's Credit amounts by filing status"
  unit: "USD"

  values:
    # Credit amounts have been frozen since 1979
    # They were temporarily suspended 2009-2011 but reinstated for 2012+
    1979-01-01:
      single: 60
      married_filing_separately: 60
      married_filing_jointly: 120
      head_of_household: 120
      qualifying_surviving_spouse: 120

  reference: "CA RTC 17081, FTB Instructions"

# =============================================================================
# AGI Limits by Filing Status
# These limits ARE adjusted annually for inflation
# =============================================================================

gov.ca.ftb.renters_credit.agi_limit:
  description: "Maximum AGI to qualify for Renter's Credit"
  unit: "USD"

  values:
    2023-01-01:
      single: 49220
      married_filing_separately: 49220
      married_filing_jointly: 98440
      head_of_household: 98440
      qualifying_surviving_spouse: 98440

    2024-01-01:
      single: 50746
      married_filing_separately: 50746
      married_filing_jointly: 101492
      head_of_household: 101492
      qualifying_surviving_spouse: 101492

    # 2025 Projected (3.1% CCPI adjustment)
    2025-01-01:
      single: 52319        # 50,746 * 1.031
      married_filing_separately: 52319
      married_filing_jointly: 104638  # 101,492 * 1.031
      head_of_household: 104638
      qualifying_surviving_spouse: 104638

    # 2026 Projected (2.5% inflation adjustment)
    2026-01-01:
      single: 53627        # 52,319 * 1.025
      married_filing_separately: 53627
      married_filing_jointly: 107254  # 104,638 * 1.025
      head_of_household: 107254
      qualifying_surviving_spouse: 107254

  reference: "FTB Form 540 Instructions"

# =============================================================================
# Notes on Renter's Credit
# =============================================================================

# Historical notes:
# - Credit enacted in 1972 as a property tax relief measure for renters
# - Credit amounts frozen at $60/$120 since 1979 (not indexed)
# - Credit was SUSPENDED for tax years 2009, 2010, and 2011 due to budget crisis
# - Reinstated for tax year 2012 and subsequent years
# - AGI limits ARE adjusted annually for inflation

# Eligibility requirements:
# - Must rent principal residence in California
# - Must pay rent for at least half the year (6 months)
# - Cannot claim if receiving Section 8 or other housing subsidies
# - Cannot claim if living in tax-exempt housing
# - Cannot claim if property is exempt from property taxes
# - Credit is nonrefundable (cannot exceed tax liability)
# - Can claim even if you don't itemize deductions

# Common disqualifying situations:
# - Living with parents/relatives who pay the rent
# - Living in a dormitory
# - Receiving government housing assistance (Section 8, public housing)
# - Living in property owned by family member
