# California Revenue and Taxation Code Section 17043
# Mental Health Services Tax Parameters
#
# Source: Proposition 63 (2004), California Mental Health Services Act
# Reference: https://ballotpedia.org/California_Proposition_63,_Tax_Increase_on_Income_Above_$1_Million_for_Mental_Health_Services_Initiative_(2004)
#
# The threshold and rate are fixed in statute (NOT indexed for inflation).
# Effective for tax years beginning on or after January 1, 2005.

metadata:
  statute: "CA RTC 17043"
  description: "Mental Health Services Tax threshold and rate"
  reference:
    - "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=17043&lawCode=RTC"
    - "https://ballotpedia.org/California_Proposition_63,_Tax_Increase_on_Income_Above_$1_Million_for_Mental_Health_Services_Initiative_(2004)"

# MHS Tax threshold - $1,000,000 (fixed in statute, not indexed)
gov.ca.ftb.mhs_tax.threshold:
  description: "Income threshold above which Mental Health Services Tax applies"
  unit: "USD"
  values:
    2005-01-01: 1000000
  reference: "CA RTC 17043"

# MHS Tax rate - 1% (fixed in statute)
gov.ca.ftb.mhs_tax.rate:
  description: "Mental Health Services Tax rate on income exceeding threshold"
  unit: "/1"
  values:
    2005-01-01: 0.01
  reference: "CA RTC 17043"

# Historical context:
# - Enacted: November 2004 (Proposition 63)
# - Effective: January 1, 2005
# - Modified: March 2024 (Proposition 1) - rebranded as Behavioral Health
#   Services Act (BHSA), expanded use of funds to include substance use
#   disorders and housing, but tax structure unchanged
#
# Note: Unlike income tax brackets, the MHS threshold is NOT adjusted
# for inflation. It has remained at $1,000,000 since 2005.
